### ISSUE TITLE
Post-token-distribution is not reflected in the UI

### ISSUE THREAD

**Issue by odd-amphora** [jbx-protocol/juice-juicehouse#98]
We should try to indicate when tokens have been distributed (& ideally how many), otherwise it's a bit confusing to the end user. 
![Screen_Shot_2021-08-20_at_1 50 44_PM](https://user-images.githubusercontent.com/88144767/130274271-addb25f4-af3f-4b31-8391-e6ed22abd097.png)

**Comment by peripheralist** [comment]
"distribute" events will eventually be added to the activity feed and will solve this. in the meantime you can still see the number of tokens available to distribute, and can't submit a TX if that number is 0. I don't see this as a big issue

If anyone has a low-effort fix for this in the meantime feel free to take it on. Otherwise i'm not going to prioritize this

**Comment by peripheralist** [comment]
distribute events are shown in the UI now
